export const groupDatas = [
  // {
  //   id: 1,
  //   name: "Roommates",
  //   members: [{ initials: "JB" }, { initials: "TA" }, { initials: "MT" }],
  //   totalExpenses: 1247.0,
  //   userBalance: 164.0,
  //   expenses: [
  //     {
  //       date: "2024-04-01",
  //       description: "Groceries",
  //       category: "Food",
  //       paidBy: "JB",
  //       amount: 120.5,
  //     },
  //     {
  //       date: "2024-04-03",
  //       description: "Electricity Bill",
  //       category: "Utilities",
  //       paidBy: "TA",
  //       amount: 80,
  //     },
  //     {
  //       date: "2024-04-06",
  //       description: "Netflix",
  //       category: "Entertainment",
  //       paidBy: "MT",
  //       amount: 30,
  //     },
  //     {
  //       date: "2024-04-09",
  //       description: "Dinner Out",
  //       category: "Food",
  //       paidBy: "JB",
  //       amount: 95.75,
  //     },
  //   ],
  // },
  // {
  //   id: 2,
  //   name: "Trip to Lagos",
  //   members: [{ initials: "AM" }, { initials: "KO" }, { initials: "LS" }],
  //   totalExpenses: 980.5,
  //   userBalance: 220.0,
  //   expenses: [
  //     {
  //       date: "2024-03-15",
  //       description: "Hotel",
  //       category: "Accommodation",
  //       paidBy: "AM",
  //       amount: 300,
  //     },
  //     {
  //       date: "2024-03-16",
  //       description: "Transport",
  //       category: "Travel",
  //       paidBy: "KO",
  //       amount: 150.5,
  //     },
  //   ],
  // },
  // {
  //   id: 3,
  //   name: "Project Team",
  //   members: [{ initials: "CE" }, { initials: "DW" }, { initials: "XZ" }],
  //   totalExpenses: 532.0,
  //   userBalance: 98.0,
  //   expenses: [
  //     {
  //       date: "2024-02-01",
  //       description: "GitHub Subscription",
  //       category: "Software",
  //       paidBy: "XZ",
  //       amount: 70,
  //     },
  //     {
  //       date: "2024-02-05",
  //       description: "Design Assets",
  //       category: "Design",
  //       paidBy: "CE",
  //       amount: 120,
  //     },
  //     {
  //       date: "2024-02-10",
  //       description: "Zoom Pro",
  //       category: "Communication",
  //       paidBy: "DW",
  //       amount: 25,
  //     },
  //   ],
  // },
  // {
  //   id: 4,
  //   name: "Wedding Squad",
  //   members: [{ initials: "RA" }, { initials: "NM" }, { initials: "UV" }],
  //   totalExpenses: 1890.0,
  //   userBalance: 410.0,
  //   expenses: [
  //     {
  //       date: "2024-01-10",
  //       description: "Decoration",
  //       category: "Event",
  //       paidBy: "RA",
  //       amount: 500,
  //     },
  //     {
  //       date: "2024-01-12",
  //       description: "Catering",
  //       category: "Food",
  //       paidBy: "NM",
  //       amount: 1000,
  //     },
  //     {
  //       date: "2024-01-15",
  //       description: "Photography",
  //       category: "Media",
  //       paidBy: "UV",
  //       amount: 390,
  //     },
  //   ],
  // },
  // {
  //   id: 5,
  //   name: "Coursemates",
  //   members: [{ initials: "KT" }, { initials: "BR" }, { initials: "OM" }],
  //   totalExpenses: 715.75,
  //   userBalance: 150.25,
  //   expenses: [
  //     {
  //       date: "2024-03-01",
  //       description: "Textbooks",
  //       category: "Education",
  //       paidBy: "OM",
  //       amount: 100.75,
  //     },
  //     {
  //       date: "2024-03-03",
  //       description: "Library Fee",
  //       category: "Education",
  //       paidBy: "KT",
  //       amount: 200,
  //     },
  //     {
  //       date: "2024-03-05",
  //       description: "Study Materials",
  //       category: "Education",
  //       paidBy: "BR",
  //       amount: 90,
  //     },
  //     {
  //       date: "2024-03-07",
  //       description: "Snacks",
  //       category: "Food",
  //       paidBy: "OM",
  //       amount: 75,
  //     },
  //   ],
  // },
  // {
  //   id: 6,
  //   name: "Startup Team",
  //   members: [{ initials: "ZD" }, { initials: "XP" }, { initials: "LY" }],
  //   totalExpenses: 1430.0,
  //   userBalance: 300.0,
  //   expenses: [
  //     {
  //       date: "2024-05-01",
  //       description: "Web Hosting",
  //       category: "Infrastructure",
  //       paidBy: "ZD",
  //       amount: 120,
  //     },
  //     {
  //       date: "2024-05-02",
  //       description: "Domain",
  //       category: "Infrastructure",
  //       paidBy: "XP",
  //       amount: 25,
  //     },
  //     {
  //       date: "2024-05-03",
  //       description: "Marketing",
  //       category: "Promotion",
  //       paidBy: "LY",
  //       amount: 400,
  //     },
  //     {
  //       date: "2024-05-04",
  //       description: "UI Kit",
  //       category: "Design",
  //       paidBy: "ZD",
  //       amount: 85,
  //     },
  //   ],
  // },
];
